version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: interview_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ai_mock_interview
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: interview_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      JWT_SECRET: production_jwt_secret_key_2026
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ai_mock_interview
    depends_on:
      - mysqldb

  frontend:
    build: ./frontend
    container_name: interview_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
